site_name: Go Tutorial
site_author: "Justin-Anthony Joco"

repo_name: justinjoco/go-tutorial
repo_url: https://github.com/justinjoco/go-tutorial

copyright:   'Copyright &copy; 2021 Justin-Anthony Joco'

theme:
  name: material
  palette:
    primary: cyan
  features:
    - navigation.sections

nav:
  - Overview: index.md
  - Basics: 
    - Building and Running Go Code: basics/building.md
  - Structs and Interfaces: 
    - Structs: structs/structs.md
    - Interfaces: structs/interfaces.md
  - Concurrency:
    - Goroutines: concurrency/goroutines.md
    - Channels: concurrency/channels.md
  
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences